name: movie_db_app_getx
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  connectivity_plus: ^5.0.2
  logger: ^2.0.2
  url_launcher: ^6.1.10
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.6
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
      - assets/images/
      - assets/icons/